DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  salt VARCHAR(250) NOT NULL,
  forename VARCHAR(250) NOT NULL,
  familyname VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) NOT NULL,
  street VARCHAR(250) NOT NULL,
  house_number INT NOT NULL
);